# Generated by Django 4.1.3 on 2022-11-17 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='задание')),
                ('content', models.TextField(blank=True, verbose_name='описание задания')),
                ('created', models.DateField(default=datetime.datetime(2022, 11, 17, 11, 7, 55, 302481, tzinfo=datetime.timezone.utc), verbose_name='дата создания')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='сделать до')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='файл')),
                ('is_complete', models.BooleanField(null=True, verbose_name='завершено')),
            ],
            options={
                'ordering': ['-finished_date'],
            },
        ),
    ]
